/*
 * Geocoding Batch
 *
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.geocoding.batch.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.geocoding.batch.Model
{
    /// <summary>
    /// PositionsRequest
    /// </summary>
    [DataContract(Name = "PositionsRequest")]
    public partial class PositionsRequest : IEquatable<PositionsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PositionsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionsRequest" /> class.
        /// </summary>
        /// <param name="positions">List of geographical positions for which to find the nearest location. (required).</param>
        public PositionsRequest(List<Position> positions = default(List<Position>))
        {
            // to ensure "positions" is required (not null)
            if (positions == null)
            {
                throw new ArgumentNullException("positions is a required property for PositionsRequest and cannot be null");
            }
            this.Positions = positions;
        }

        /// <summary>
        /// List of geographical positions for which to find the nearest location.
        /// </summary>
        /// <value>List of geographical positions for which to find the nearest location.</value>
        [DataMember(Name = "positions", IsRequired = true, EmitDefaultValue = true)]
        public List<Position> Positions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PositionsRequest {\n");
            sb.Append("  Positions: ").Append(Positions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PositionsRequest);
        }

        /// <summary>
        /// Returns true if PositionsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PositionsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PositionsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Positions == input.Positions ||
                    this.Positions != null &&
                    input.Positions != null &&
                    this.Positions.SequenceEqual(input.Positions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Positions != null)
                {
                    hashCode = (hashCode * 59) + this.Positions.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
