/*
 * Geocoding Batch
 *
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.geocoding.batch.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.geocoding.batch.Model
{
    /// <summary>
    /// Enumeration to specify the type of total score calculation.    * &#x60;INPUT_AND_RESULT_BASED&#x60; - The total score is calculated by comparing the result against the input.    * &#x60;RESULT_BASED&#x60; - The total score is calculated by classifying result attributes.      This parameter is experimental and may change at any time in the future.
    /// </summary>
    /// <value>Enumeration to specify the type of total score calculation.    * &#x60;INPUT_AND_RESULT_BASED&#x60; - The total score is calculated by comparing the result against the input.    * &#x60;RESULT_BASED&#x60; - The total score is calculated by classifying result attributes.      This parameter is experimental and may change at any time in the future.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TotalScoreType
    {
        /// <summary>
        /// Enum INPUT_AND_RESULT_BASED for value: INPUT_AND_RESULT_BASED
        /// </summary>
        [EnumMember(Value = "INPUT_AND_RESULT_BASED")]
        INPUT_AND_RESULT_BASED = 1,

        /// <summary>
        /// Enum RESULT_BASED for value: RESULT_BASED
        /// </summary>
        [EnumMember(Value = "RESULT_BASED")]
        RESULT_BASED = 2
    }

}
