/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding Batch
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressProperties } from './AddressProperties';
import {
    AddressPropertiesFromJSON,
    AddressPropertiesFromJSONTyped,
    AddressPropertiesToJSON,
} from './AddressProperties';

/**
 * 
 * @export
 * @interface AddressesRequest
 */
export interface AddressesRequest {
    /**
     * List of multi-field address inputs that describe a location.
     * @type {Array<AddressProperties>}
     * @memberof AddressesRequest
     */
    addresses: Array<AddressProperties>;
}

/**
 * Check if a given object implements the AddressesRequest interface.
 */
export function instanceOfAddressesRequest(value: object): value is AddressesRequest {
    if (!('addresses' in value) || value['addresses'] === undefined) return false;
    return true;
}

export function AddressesRequestFromJSON(json: any): AddressesRequest {
    return AddressesRequestFromJSONTyped(json, false);
}

export function AddressesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': ((json['addresses'] as Array<any>).map(AddressPropertiesFromJSON)),
    };
}

export function AddressesRequestToJSON(value?: AddressesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'addresses': ((value['addresses'] as Array<any>).map(AddressPropertiesToJSON)),
    };
}

