/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding Batch
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Warning } from './Warning';
import {
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
} from './ErrorResponse';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * The result of a locations search.
 * @export
 * @interface LocationsSearchResult
 */
export interface LocationsSearchResult {
    /**
     * The found locations.
     * @type {Array<Location>}
     * @memberof LocationsSearchResult
     */
    locations?: Array<Location>;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof LocationsSearchResult
     */
    warnings?: Array<Warning>;
    /**
     * 
     * @type {ErrorResponse}
     * @memberof LocationsSearchResult
     */
    error?: ErrorResponse;
}

/**
 * Check if a given object implements the LocationsSearchResult interface.
 */
export function instanceOfLocationsSearchResult(value: object): value is LocationsSearchResult {
    return true;
}

export function LocationsSearchResultFromJSON(json: any): LocationsSearchResult {
    return LocationsSearchResultFromJSONTyped(json, false);
}

export function LocationsSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'locations': json['locations'] == null ? undefined : ((json['locations'] as Array<any>).map(LocationFromJSON)),
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
        'error': json['error'] == null ? undefined : ErrorResponseFromJSON(json['error']),
    };
}

export function LocationsSearchResultToJSON(value?: LocationsSearchResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'locations': value['locations'] == null ? undefined : ((value['locations'] as Array<any>).map(LocationToJSON)),
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(WarningToJSON)),
        'error': ErrorResponseToJSON(value['error']),
    };
}

