/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding Batch
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoadAccessPosition } from './RoadAccessPosition';
import {
    RoadAccessPositionFromJSON,
    RoadAccessPositionFromJSONTyped,
    RoadAccessPositionToJSON,
} from './RoadAccessPosition';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';
import type { Quality } from './Quality';
import {
    QualityFromJSON,
    QualityFromJSONTyped,
    QualityToJSON,
} from './Quality';
import type { LocationType } from './LocationType';
import {
    LocationTypeFromJSON,
    LocationTypeFromJSONTyped,
    LocationTypeToJSON,
} from './LocationType';
import type { ReferencePosition } from './ReferencePosition';
import {
    ReferencePositionFromJSON,
    ReferencePositionFromJSONTyped,
    ReferencePositionToJSON,
} from './ReferencePosition';

/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {ReferencePosition}
     * @memberof Location
     */
    referencePosition: ReferencePosition;
    /**
     * 
     * @type {RoadAccessPosition}
     * @memberof Location
     */
    roadAccessPosition?: RoadAccessPosition;
    /**
     * 
     * @type {Address}
     * @memberof Location
     */
    address: Address;
    /**
     * A single string representing the address, typically consisting of the street, house number, postal code, city, and country. The precise format may differ based on what is appropriate for the address.
     * @type {string}
     * @memberof Location
     */
    formattedAddress?: string;
    /**
     * 
     * @type {LocationType}
     * @memberof Location
     */
    locationType: LocationType;
    /**
     * 
     * @type {Quality}
     * @memberof Location
     */
    quality: Quality;
}



/**
 * Check if a given object implements the Location interface.
 */
export function instanceOfLocation(value: object): value is Location {
    if (!('referencePosition' in value) || value['referencePosition'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('locationType' in value) || value['locationType'] === undefined) return false;
    if (!('quality' in value) || value['quality'] === undefined) return false;
    return true;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if (json == null) {
        return json;
    }
    return {
        
        'referencePosition': ReferencePositionFromJSON(json['referencePosition']),
        'roadAccessPosition': json['roadAccessPosition'] == null ? undefined : RoadAccessPositionFromJSON(json['roadAccessPosition']),
        'address': AddressFromJSON(json['address']),
        'formattedAddress': json['formattedAddress'] == null ? undefined : json['formattedAddress'],
        'locationType': LocationTypeFromJSON(json['locationType']),
        'quality': QualityFromJSON(json['quality']),
    };
}

export function LocationToJSON(value?: Location | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'referencePosition': ReferencePositionToJSON(value['referencePosition']),
        'roadAccessPosition': RoadAccessPositionToJSON(value['roadAccessPosition']),
        'address': AddressToJSON(value['address']),
        'formattedAddress': value['formattedAddress'],
        'locationType': LocationTypeToJSON(value['locationType']),
        'quality': QualityToJSON(value['quality']),
    };
}

