/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding Batch
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';

/**
 * 
 * @export
 * @interface PositionsRequest
 */
export interface PositionsRequest {
    /**
     * List of geographical positions for which to find the nearest location.
     * @type {Array<Position>}
     * @memberof PositionsRequest
     */
    positions: Array<Position>;
}

/**
 * Check if a given object implements the PositionsRequest interface.
 */
export function instanceOfPositionsRequest(value: object): value is PositionsRequest {
    if (!('positions' in value) || value['positions'] === undefined) return false;
    return true;
}

export function PositionsRequestFromJSON(json: any): PositionsRequest {
    return PositionsRequestFromJSONTyped(json, false);
}

export function PositionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'positions': ((json['positions'] as Array<any>).map(PositionFromJSON)),
    };
}

export function PositionsRequestToJSON(value?: PositionsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'positions': ((value['positions'] as Array<any>).map(PositionToJSON)),
    };
}

