/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding Batch API
 * With the Batch Geocoding service you can find a large number of locations.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextsRequest
 */
export interface TextsRequest {
    /**
     * List of free-form text inputs that describe a location.
     * @type {Array<string>}
     * @memberof TextsRequest
     */
    texts: Array<string>;
}

/**
 * Check if a given object implements the TextsRequest interface.
 */
export function instanceOfTextsRequest(value: object): value is TextsRequest {
    if (!('texts' in value) || value['texts'] === undefined) return false;
    return true;
}

export function TextsRequestFromJSON(json: any): TextsRequest {
    return TextsRequestFromJSONTyped(json, false);
}

export function TextsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'texts': json['texts'],
    };
}

export function TextsRequestToJSON(value?: TextsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'texts': value['texts'],
    };
}

